# Generated by Django 5.2.5 on 2025-09-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
