# Generated by Django 5.2.5 on 2025-09-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0002_emp_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
